name: Publish Python 🐍 distribution 📦 (to PyPI [later!]) and TestPyPI
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

on:
  pull_request:
  workflow_run:
    workflows: [hosted-pure-workflow]
    types:
      - completed

jobs:
  build:
    name: Build distribution 📦
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version : ["3.8", "3.9", "3.10", "3.11", "3.x"]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx

    steps:
    - name: Move build files to package directory
      run: cp build/ninja-multi-vcpkg/cpp/src/Release/* stabiliser-tools/dist/stab_tools/
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Go to package directory
      run: cd stabiliser-tools
    - name: Build a binary wheel and a source tarball
      run: python3 -m build stabiliser-tools/
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: stabiliser-tools/dist/

  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs:
    - build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version : ["3.8", "3.9", "3.10", "3.11", "3.x"]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx

    environment:
      name: testpypi
      url: https://test.pypi.org/p/stabiliser-tools

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: stabiliser-tools/dist/
    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        packages-dir: stabiliser-tools/dist/